<a href="https://colab.research.google.com/github/UCD-Physics/Python-HowTos/blob/main/Numpy-vs-StandardPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy vs Standard Python

Numpy should be preferred over standard Python lists and looping for performing calculations or arrays of numbers since Numpy is optimised for array-wise operations making code easier to write and read with less errors, and it executes much faster.

This notebook demonstrates some of the main benefits of using Numpy for array-wise calculations. 

Note: Numpy replaces the math library - both are included here as we compare the two.

In [7]:
import numpy as np
import math

## Make a range of numbers in numpy

`np.arange()` arguments are: `end` or `start, end` or `start, end, step`.

Notes: 
 * `end` is not included.
 * values do not have to be integers
 
Examples:

In [8]:
xn = np.arange(10)
xn

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
xn = np.arange(0.1,10,0.5)
xn

array([0.1, 0.6, 1.1, 1.6, 2.1, 2.6, 3.1, 3.6, 4.1, 4.6, 5.1, 5.6, 6.1,
       6.6, 7.1, 7.6, 8.1, 8.6, 9.1, 9.6])

## Array-wise calculations using standard arithmetic and numpy functions!

In [10]:
xn**2

array([1.000e-02, 3.600e-01, 1.210e+00, 2.560e+00, 4.410e+00, 6.760e+00,
       9.610e+00, 1.296e+01, 1.681e+01, 2.116e+01, 2.601e+01, 3.136e+01,
       3.721e+01, 4.356e+01, 5.041e+01, 5.776e+01, 6.561e+01, 7.396e+01,
       8.281e+01, 9.216e+01])

### even for your own functions!

In [11]:
def my_fnc(x):
    return x**3 + np.cos(x) + 3

In [12]:
my_fnc(xn)

array([  3.99600417,   4.04133561,   4.78459612,   7.06680048,
        11.7561539 ,  19.71911125,  31.79186485,  48.75924158,
        71.34617605, 100.22384747, 136.02897774, 179.39156588,
       230.96426844, 291.44623259, 361.59554667, 442.22725984,
       534.19745585, 638.37727995, 755.6232784 , 886.75131214])

## Numpy is much faster than looping!

Notes, the command used below for timing `%%timeit` is a [cell magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics) command. There is also [line magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#line-magics)


### test speed of numpy...

In [32]:
N = 1_000_000

xn = np.linspace(0, 10, N)

In [33]:
%%timeit  
# %%timeit times how long it takes to run the cell 
# multiple times and calculates averagre and std dev.

yn = np.cos(xn) ** 2

9.39 ms ± 87.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### test speed of Python using List Comprehension

In [34]:
N = 1_000_000

step = (10 - 0) / N

x = [i * step for i in range(N + 1)]

In [35]:
%%timeit

y = [math.cos(xi) ** 2 for xi in x]

173 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### test speed of pythons using list and append

using already defined `x` list...

In [36]:
%%timeit

N = 1_000_000

y = []

for xi in range(N + 1):
    y.append(math.cos(xi) ** 2)

222 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Complete examples 

### Complete examples in standard Python using Loops

In [37]:
%%timeit

N = 1_000_000
step = (10 - 0) / N

x = []
y = []

for xi in range(N + 1):
    x.append(xi * step)
    y.append(math.cos(xi) ** 2)

317 ms ± 4.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Complete example in standard Python using List Comprehension

In [27]:
%%timeit

N = 1_000_000

step = (10 - 0) / N

x = [i * step for i in range(N + 1)]
y = [math.cos(xi) ** 2 for xi in x]

242 ms ± 1.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Complete example in Numpy

In [39]:
%%timeit

N = 1_000_000

xn = np.linspace(0, 10, N)
yn = np.cos(xn) ** 2

10.9 ms ± 31.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Summary: learn and use Numpy

For doing calculations on arrays of numbers NumPy is preferable for the following reasons:
 * Code is more compact, less error prone and easier to read
 * The code may execute many times faster (x10+) without having to do anything other than use numpy arrays
 * Numpy is extensive and powerful (e.g. 2D arrays, array, column-wise, row-wise and matrix operations, conditions ...)
 * Many libraries are built to use Numpy Arrays (e.g. SciPy, AstroPy....)

## Cavaets

Numpy arrays cannot be extended once made - values stored in the array can be changed but the size of the array cannot. 

Please read help on functions you use and understand what is happening!

Example: sequential operations such as taking data in a loop or iterative calculations that cannot be done array wise. Many people use `np.append()`....

It is better to use a Python list and append to it or, if you know how many points will be needed, then pre-allocate the numpy array and fill the values using indices.  

### Appending to a Python list:

In [40]:
%%timeit

N = 1_000_000

x = []

for i in range(N):
    x.append(i/2)

95.5 ms ± 883 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Filling a pre-allocated NumPy array:

In [41]:
%%timeit

N = 1_000_000

x = np.empty(N, dtype=float)

for i in range(N):
    x[i] = i/2

109 ms ± 6.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Numpy.append() - do not use this in a loop with a lot of appends!

The cell below takes a very long time to run.....

In [ ]:
%%timeit

N = 1_000_000

xn = np.array([], dtype=float)

for i in range(N):
    xn = np.append(xn, i/2)